on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  id-token: write

name: release-please

jobs:
  report-main-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup and install
        uses: ./.github/actions/setup-and-install

      - name: Test
        run: pnpm coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  release-please:
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        if: ${{ github.ref_name == 'main' }}
        with:
          release-type: node
          package-name: lib-address
          changelog-notes-type: github

  release-npm-package:
    needs: release-please
    runs-on: ubuntu-latest
    if: ${{ needs.release-please.outputs.releases_created }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup and install
        uses: ./.github/actions/setup-and-install

      - name: Build
        run: pnpm build

      - run: npm install -g npm

      - name: Publish to npm latest
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
